name: Kali Linux SSH

on:
  workflow_dispatch:   # supaya bisa dijalankan manual

env:
  TZ: Asia/Kolkata
  GIT_USERNAME: AiraaCheisyaa
  GIT_EMAIL: iraa@gmail.com

jobs:
  kali-ssh:
    name: Kali Linux SSH
    runs-on: ubuntu-latest
    timeout-minutes: 120

    container:
      image: kalilinux/kali-rolling:latest
      options: --cpus 2 --memory 6g   # <= Fix limit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          apt update
          apt install sudo apt-utils -y
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
          ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
          apt-get install -y tzdata
          dpkg-reconfigure --frontend noninteractive tzdata
          sudo apt update -y && sudo apt install git aria2 curl wget tmate rsync zip unzip lzma cpio ccache neofetch openssh-server -y
          sudo apt install python2 -y
          sudo ln -sf /usr/bin/python2 /usr/bin/python
          git config --global user.name "$GIT_USERNAME"
          git config --global user.email "$GIT_EMAIL"

      - name: Run Tmate Script
        run: bash tmate.sh

      - name: Run Spam Script
        run: bash spam.sh
